### PR TITLE
fixed #3

### LINKED ISSUE #3: Incorrect @return broke PHPStorm autocomplete
In `\BehEh\Flaps\Flaps::getFlap` given incorrect PHPDoc: leading backslash missed and this broke PHPStorm' autocomplete (see attached screenshot). IDE resolves BehEh\Flaps\Flap as nested namespace \BehEh\Flaps\Flaps\BehEh\Flaps\Flap.
If I add backslash in @return autocomplete works fine.

``` php
    /**
     * Creates a new Flap and returns it, setting default violation handler.,
     * @param string $name the name of the flap
     * @return BehEh\Flaps\Flap the created flap here <- here
     */
```

### PR DESCRIPTION
**Pull request by Icewild**

### CODE REVIEW

**Comment by beheh** [comment]
Landed as of 57b39f263955a9be2580d5aeafd2249116f9e04e.

**Comment by beheh** [comment]
Thanks for the PR!

**Comment by Icewild** [comment]
@beheh You closed PR, but not merged it. I think you missclicked?

**Comment by beheh** [comment]
I merged it, but I reworded the commit messages - that's why GitHub did not recognize the PR as being merged.  The commits are in [master](https://github.com/beheh/flaps/commits/master) and attributed to you.

**Pull request closed without merging**
